package com.xiaobin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCompany<M extends BaseCompany<M>> extends Model<M> implements IBean {

	public void setCompanyId(java.lang.String companyId) {
		set("company_id", companyId);
	}

	public java.lang.String getCompanyId() {
		return get("company_id");
	}

	public void setCompanyName(java.lang.String companyName) {
		set("company_name", companyName);
	}

	public java.lang.String getCompanyName() {
		return get("company_name");
	}

	public void setIndustry(java.lang.String industry) {
		set("industry", industry);
	}

	public java.lang.String getIndustry() {
		return get("industry");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setFax(java.lang.String fax) {
		set("fax", fax);
	}

	public java.lang.String getFax() {
		return get("fax");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setNotes(java.lang.String notes) {
		set("notes", notes);
	}

	public java.lang.String getNotes() {
		return get("notes");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

	public void setCreateTime(java.sql.Timestamp createTime) {
		set("create_time", createTime);
	}

	public java.sql.Timestamp getCreateTime() {
		return get("create_time");
	}

	public void setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
	}

	public java.lang.String getUpdateUser() {
		return get("update_user");
	}

	public void setUpdateTime(java.sql.Timestamp updateTime) {
		set("update_time", updateTime);
	}

	public java.sql.Timestamp getUpdateTime() {
		return get("update_time");
	}

}
