package com.xiaobin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProduct<M extends BaseProduct<M>> extends Model<M> implements IBean {

	public void setProdId(java.lang.String prodId) {
		set("prod_id", prodId);
	}

	public java.lang.String getProdId() {
		return get("prod_id");
	}

	public void setProdName(java.lang.String prodName) {
		set("prod_name", prodName);
	}

	public java.lang.String getProdName() {
		return get("prod_name");
	}

	public void setParentId(java.lang.String parentId) {
		set("parent_id", parentId);
	}

	public java.lang.String getParentId() {
		return get("parent_id");
	}

	public void setProdType(java.lang.String prodType) {
		set("prod_type", prodType);
	}

	public java.lang.String getProdType() {
		return get("prod_type");
	}

	public void setProdLevel(java.lang.String prodLevel) {
		set("prod_level", prodLevel);
	}

	public java.lang.String getProdLevel() {
		return get("prod_level");
	}

	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}

	public java.lang.String getIcon() {
		return get("icon");
	}

}
