package com.xiaobin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWeekreportOvertime<M extends BaseWeekreportOvertime<M>> extends Model<M> implements IBean {

	public void setWorkTime(java.lang.String workTime) {
		set("work_time", workTime);
	}

	public java.lang.String getWorkTime() {
		return get("work_time");
	}

	public void setOverTimeBegin(java.lang.String overTimeBegin) {
		set("over_time_begin", overTimeBegin);
	}

	public java.lang.String getOverTimeBegin() {
		return get("over_time_begin");
	}

	public void setOverTimeEnd(java.lang.String overTimeEnd) {
		set("over_time_end", overTimeEnd);
	}

	public java.lang.String getOverTimeEnd() {
		return get("over_time_end");
	}

}
