package com.xiaobin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProjectInfo<M extends BaseProjectInfo<M>> extends Model<M> implements IBean {

	public void setProjectId(java.lang.String projectId) {
		set("project_id", projectId);
	}

	public java.lang.String getProjectId() {
		return get("project_id");
	}

	public void setParentId(java.lang.String parentId) {
		set("parent_id", parentId);
	}

	public java.lang.String getParentId() {
		return get("parent_id");
	}

	public void setProjectName(java.lang.String projectName) {
		set("project_name", projectName);
	}

	public java.lang.String getProjectName() {
		return get("project_name");
	}

	public void setDevelopCompany(java.lang.String developCompany) {
		set("develop_company", developCompany);
	}

	public java.lang.String getDevelopCompany() {
		return get("develop_company");
	}

	public void setCustomer(java.lang.String customer) {
		set("customer", customer);
	}

	public java.lang.String getCustomer() {
		return get("customer");
	}

	public void setExpectStartTime(java.lang.String expectStartTime) {
		set("expect_start_time", expectStartTime);
	}

	public java.lang.String getExpectStartTime() {
		return get("expect_start_time");
	}

	public void setStartTime(java.lang.String startTime) {
		set("start_time", startTime);
	}

	public java.lang.String getStartTime() {
		return get("start_time");
	}

	public void setEndTime(java.lang.String endTime) {
		set("end_time", endTime);
	}

	public java.lang.String getEndTime() {
		return get("end_time");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

	public void setCreateTime(java.sql.Timestamp createTime) {
		set("create_time", createTime);
	}

	public java.sql.Timestamp getCreateTime() {
		return get("create_time");
	}

	public void setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
	}

	public java.lang.String getUpdateUser() {
		return get("update_user");
	}

	public void setUpdateTime(java.sql.Timestamp updateTime) {
		set("update_time", updateTime);
	}

	public java.sql.Timestamp getUpdateTime() {
		return get("update_time");
	}

	public void setExpectEndTime(java.lang.String expectEndTime) {
		set("expect_end_time", expectEndTime);
	}

	public java.lang.String getExpectEndTime() {
		return get("expect_end_time");
	}

}
