package com.xiaobin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserOperate<M extends BaseUserOperate<M>> extends Model<M> implements IBean {

	public void setOperateId(java.lang.String operateId) {
		set("operate_id", operateId);
	}

	public java.lang.String getOperateId() {
		return get("operate_id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public void setOperate(java.lang.String operate) {
		set("operate", operate);
	}

	public java.lang.String getOperate() {
		return get("operate");
	}

	public void setTime1(java.lang.String time1) {
		set("time1", time1);
	}

	public java.lang.String getTime1() {
		return get("time1");
	}

	public void setTime2(java.lang.String time2) {
		set("time2", time2);
	}

	public java.lang.String getTime2() {
		return get("time2");
	}

	public void setNotes(java.lang.String notes) {
		set("notes", notes);
	}

	public java.lang.String getNotes() {
		return get("notes");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

	public void setCreateTime(java.sql.Timestamp createTime) {
		set("create_time", createTime);
	}

	public java.sql.Timestamp getCreateTime() {
		return get("create_time");
	}

}
