package com.xiaobin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWeekreport<M extends BaseWeekreport<M>> extends Model<M> implements IBean {

	public void setReportId(java.lang.String reportId) {
		set("report_id", reportId);
	}

	public java.lang.String getReportId() {
		return get("report_id");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setRemainProblems(java.lang.String remainProblems) {
		set("remain_problems", remainProblems);
	}

	public java.lang.String getRemainProblems() {
		return get("remain_problems");
	}

	public void setIsTrip(java.lang.String isTrip) {
		set("is_trip", isTrip);
	}

	public java.lang.String getIsTrip() {
		return get("is_trip");
	}

	public void setWorkSuggest(java.lang.String workSuggest) {
		set("work_suggest", workSuggest);
	}

	public java.lang.String getWorkSuggest() {
		return get("work_suggest");
	}

	public void setNotes(java.lang.String notes) {
		set("notes", notes);
	}

	public java.lang.String getNotes() {
		return get("notes");
	}

	public void setPmoEmail(java.lang.String pmoEmail) {
		set("pmo_email", pmoEmail);
	}

	public java.lang.String getPmoEmail() {
		return get("pmo_email");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

	public void setCreateTime(java.sql.Timestamp createTime) {
		set("create_time", createTime);
	}

	public java.sql.Timestamp getCreateTime() {
		return get("create_time");
	}

	public void setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
	}

	public java.lang.String getUpdateUser() {
		return get("update_user");
	}

	public void setUpdateTime(java.sql.Timestamp updateTime) {
		set("update_time", updateTime);
	}

	public java.sql.Timestamp getUpdateTime() {
		return get("update_time");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setWorkTime(java.sql.Timestamp workTime) {
		set("work_time", workTime);
	}

	public java.sql.Timestamp getWorkTime() {
		return get("work_time");
	}

}
