package com.xiaobin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserAttr<M extends BaseUserAttr<M>> extends Model<M> implements IBean {

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public void setAttrType(java.lang.String attrType) {
		set("attr_type", attrType);
	}

	public java.lang.String getAttrType() {
		return get("attr_type");
	}

	public void setAttrId(java.lang.String attrId) {
		set("attr_id", attrId);
	}

	public java.lang.String getAttrId() {
		return get("attr_id");
	}

	public void setAttrValue(java.lang.String attrValue) {
		set("attr_value", attrValue);
	}

	public java.lang.String getAttrValue() {
		return get("attr_value");
	}

	public void setAttrDesc(java.lang.String attrDesc) {
		set("attr_desc", attrDesc);
	}

	public java.lang.String getAttrDesc() {
		return get("attr_desc");
	}

}
