package com.xiaobin.model.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("SOAP_COMPANY", "COMPANY_ID", Company.class);
		arp.addMapping("SOAP_PRODUCT", "PROD_ID", Product.class);
		arp.addMapping("SOAP_PROJECT_FUNCTIONS", "FUNCTION_ID", ProjectFunctions.class);
		arp.addMapping("SOAP_PROJECT_INFO", "PROJECT_ID", ProjectInfo.class);
		// Composite Primary Key order: FUNCTION_ID,PROJECT_ID,STATUS,USER_ID
		arp.addMapping("SOAP_PROJECT_USERS", "FUNCTION_ID,PROJECT_ID,STATUS,USER_ID", ProjectUsers.class);
		arp.addMapping("SOAP_USERS", "USER_ID", Users.class);
		// Composite Primary Key order: ATTR_ID,ATTR_TYPE,USER_ID
		arp.addMapping("SOAP_USER_ATTR", "ATTR_ID,ATTR_TYPE,USER_ID", UserAttr.class);
		arp.addMapping("SOAP_USER_OPERATE", "OPERATE_ID", UserOperate.class);
		arp.addMapping("SOAP_WEEKREPORT", "REPORT_ID", Weekreport.class);
		arp.addMapping("SOAP_WEEKREPORT_OVERTIME", "WORK_TIME", WeekreportOvertime.class);
	}
}

