package com.xiaobin.model.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("SOAP_PRODUCT", "PROD_ID", Product.class);
		arp.addMapping("SOAP_USERS", "USER_ID", Users.class);
		arp.addMapping("SOAP_WEEKREPORT", "REPORT_ID", Weekreport.class);
		arp.addMapping("SOAP_WEEKREPORT_OVERTIME", "WORK_TIME", WeekreportOvertime.class);
	}
}

