package com.xiaobin.model.model;

import com.xiaobin.model.base.BaseCodes;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Codes extends BaseCodes<Codes> {
	public static final Codes dao = new Codes().dao();
}
