package com.xiaobin.model.model;

import com.jfinal.kit.Prop;
import com.xiaobin.model.base.BaseProjectInfo;
import com.xiaobin.util.Util;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectInfo extends BaseProjectInfo<ProjectInfo> {
	public static final ProjectInfo dao = new ProjectInfo().dao();

	public List<ProjectInfo> page(ProjectInfo info){
		Prop p = Util.getProp("dao/projectManage/projectInfo");
		return find(p.get("query"));
	}
}
