package com.xiaobin.model.model;

import com.jfinal.kit.Prop;
import com.xiaobin.model.base.BaseUsers;
import com.xiaobin.util.SUtil;
import com.xiaobin.util.Util;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Users extends BaseUsers<Users> {
	public static final Users dao = new Users().dao();

	public List<Users> query(Users users){
		Prop p = Util.getProp("dao/sys/users");
		SUtil sUtil = new SUtil(users.toRecord());
		sUtil.condition("u");
		return find(p.get("query") + sUtil.getSql(),sUtil.getValues().toArray());
	}

	public List<Users> queryCurrent(Users users){
		Prop p = Util.getProp("dao/sys/users");
		String select = p.get("query");
		select += " and status < 80";
		return find(select);
	}

	public List<Users> queryHis(Users users){
		Prop p = Util.getProp("dao/sys/users");
		String select = p.get("query");
		select += "and status >= 80";
		return find(select);
	}
}
