package com.xiaobin.model.model;

import com.jfinal.kit.Prop;
import com.xiaobin.model.base.BaseUsers;
import com.xiaobin.util.Util;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Users extends BaseUsers<Users> {
	public static final Users dao = new Users().dao();

	public List<Users> query(Users users){
		Prop p = Util.getProp("dao/sys/users");
		return find(p.get("query"));
	}
}
