package com.xiaobin.model.model;

import com.xiaobin.model.base.BaseUserOperate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserOperate extends BaseUserOperate<UserOperate> {
	public static final UserOperate dao = new UserOperate().dao();
}
