package com.xiaobin.model.model;

import com.xiaobin.model.base.BaseUserAttr;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserAttr extends BaseUserAttr<UserAttr> {
	public static final UserAttr dao = new UserAttr().dao();
}
